#!/usr/bin/env zsh

if [[ $# -ne 2 ]]; then
  echo "Usage: ${0:t} author repo"
  exit 1
fi

rootdir=${0:a:h:h}
cd ${rootdir}
pack_author=$1
pack_name=$2

submodule_glob="nvim/pack/${pack_author}/*/${pack_name}"
submodule_path=(${^~submodule_glob})
gitmodule_path=.git/modules/${submodule_path}

setopt err_exit
setopt verbose
git submodule deinit -f ${submodule_path}

git rm -rf ${submodule_path}
rm -rf ${gitmodule_path}

# If the kind dirs are now empty, remove them
rmdir ${submodule_path:h}
rmdir ${gitmodule_path:h}

# If the author dirs are now empty, remove them
rmdir ${submodule_path:h:h}
rmdir ${gitmodule_path:h:h}


