thisdir=$0:a:h
export EDITOR=nvim
export VISUAL=nvim
export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker
export CLICOLOR=true

# Enable vim command mode with 0.1s lag
bindkey -v
export KEYTIMEOUT=1

setopt autocd

autoload -U colors
colors

typeset -gU cdpath fpath path
cdpath=(~ $cdpath)

autoload -U +X compinit
compinit -d $ZSH_DATA_HOME/.zcompdump
compdef _gradle gw

jdk () { export JAVA_HOME=$(/usr/libexec/java_home -v "$@"); }
ww() { which "$@" && readlink $(which "$@") || true ; }

eval "$(direnv hook zsh)"

. $thisdir/aliases.zsh
. $thisdir/prompt.zsh
