export EDITOR=nvim
export VISUAL=nvim
export PAGER='less -FRX'
export CLICOLOR=true

# Enable vim command mode with 0.1s lag
bindkey -v
export KEYTIMEOUT=1

setopt autocd

autoload -U colors
colors

typeset -gU cdpath fpath path
cdpath=(~ $cdpath)

autoload -U +X compinit
compinit -d $ZSH_DATA_HOME/.zcompdump
compdef _gradle gw

JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null)
[[ $? -eq 0 ]] && export JAVA_HOME

eval "$(direnv hook zsh)"

thisdir=$0:a:h
. $thisdir/aliases.zsh
. $thisdir/prompt.zsh
